### ISSUE TITLE
🐛[BUG] 您好，这个报错应该怎么解决呢

### ISSUE THREAD

**Issue by my-pku** [misaka10843/copymanga-downloader#18]
Traceback (most recent call last):
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002226321C940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.copymanga.info', port=443): Max retries exceeded with url: /api/v3/search/comic?format=json&limit=20&offset=0&platform=3&q=%E8%93%9D%E8%89%B2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002226321C940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\2D\copymanga-downloader-master\main.py", line 300, in <module>
    welcome()
  File "E:\2D\copymanga-downloader-master\main.py", line 294, in welcome
    manga_search(manga_name)
  File "E:\2D\copymanga-downloader-master\main.py", line 95, in manga_search
    response = requests.get(
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\2D\copymanga-downloader-master\venv\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.copymanga.info', port=443): Max retries exceeded with url: /api/v3/search/comic?format=json&limit=20&offset=0&platform=3&q=%E8%93%9D%E8%89%B2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002226321C940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

Process finished with exit code 1

**Comment by misaka10843** [comment]
似乎是因为访问过于频繁导致的临时ban了
可以尝试用代理或者过段时间试试qwq

**Comment by my-pku** [comment]
喔喔谢谢

**Comment by misaka10843** [comment]
如果按照上述方法实施后还出现这种问题就再重新打开这个issue吧qwq

**Comment by my-pku** [comment]
喔喔，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月29日 19:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [misaka10843/copymanga-downloader] 🐛[BUG] 您好，这个报错应该怎么解决呢 (Issue #18) |

似乎是因为访问过于频繁导致的临时ban了
可以尝试用代理或者过段时间试试qwq
