### ISSUE TITLE
👑[Enhancement] 支持导出用户收藏漫画

### ISSUE THREAD

**Issue by Aik-R** [misaka10843/copymanga-downloader#19]
请问作者大大未来能否支持将用户收藏的漫画导出至本地保存呢？
咱就是害怕会有 不可抗力(? 导致多年收藏的漫画就此不见QAQ
咱也不懂啥技术，就只能单纯的提提需求了{{{(>_<)}}}

**Comment by misaka10843** [comment]
具体是想纯粹的导出标题还是？

**Comment by Aik-R** [comment]
只要能将标题导出就好了(o゜▽゜)o☆

**Comment by misaka10843** [comment]
ok，但是可能最多提取前500个（毕竟多了对服务器有点压力www）

**Comment by Aik-R** [comment]
感谢作者大大 ( •̀ ω •́ )✧ 辛苦了

**Comment by misaka10843** [comment]
现在已经支持输出500个以内的漫画名了qwq

**Comment by misaka10843** [comment]
https://github.com/misaka10843/copymanga-downloader/actions/runs/2327075594
这里即可下载最新的编译程序qwq

**Comment by Aik-R** [comment]
感谢作者大大！！ 太棒了♪(^∇^*)

**Comment by misaka10843** [comment]
因为发现有时候会出现报错，所以重新改了下，顺便添加了csv，方便在Excel查看qwq
https://github.com/misaka10843/copymanga-downloader/actions/runs/2458893476

**Comment by Aik-R** [comment]
感谢作者大大的修复！

**Comment by blacklein** [comment]
```
您是想搜索还是查看您的收藏？(0:导出收藏,1:搜索,2:收藏  默认1):0
Traceback (most recent call last):
  File "main.py", line 441, in <module>
  File "main.py", line 432, in welcome
  File "main.py", line 388, in manga_collection_backup
NameError: name 'Authorization' is not defined
[61212] Failed to execute script 'main' due to unhandled exception!
```

```
您是想搜索还是查看您的收藏？(0:导出收藏,1:搜索,2:收藏  默认1):2
Traceback (most recent call last):
  File "main.py", line 441, in <module>
  File "main.py", line 430, in welcome
  File "main.py", line 334, in manga_collection
NameError: name 'Authorization' is not defined
[61275] Failed to execute script 'main' due to unhandled exception!
```

M1 Max Macbook Pro 填入Token（包含`Token`）后选择导出收藏、收藏两个选项均报错，用Rlease的x86_64和本地build的arm64的版本报错信息相同，因此猜测应该和处理器架构无关
