### ISSUE TITLE
👑[Enhancement] macOS用pyinstaller将main.py打包成executable binary后运行报错

### ISSUE THREAD

**Issue by blacklein** [misaka10843/copymanga-downloader#29]
### 🥰 需求描述(Description)
macOS用pyinstaller将main.py打包成executable binary，打包成功，但用终端运行binary报错
**希望大佬在仓库源码中提供一个可用于pyinstaller打包的main.spec文件**

**安装依赖**
```
❯ pip3 install -r requirements.txt
Requirement already satisfied: requests~=2.26.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.26.0)
Requirement already satisfied: tqdm~=4.62.3 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (4.62.3)
Requirement already satisfied: pysocks~=1.7.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.7.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from requests~=2.26.0->-r requirements.txt (line 1)) (2022.5.18.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from requests~=2.26.0->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from requests~=2.26.0->-r requirements.txt (line 1)) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from requests~=2.26.0->-r requirements.txt (line 1)) (2.0.4)
```

**生成main.spec**
```
❯ pyinstaller -F main.py
125 INFO: PyInstaller: 5.1
125 INFO: Python: 3.9.13
132 INFO: Platform: macOS-12.4-arm64-arm-64bit
133 INFO: wrote /Users/chenzhiyu/Downloads/copymanga-downloader/main.spec
140 INFO: UPX is available.
141 INFO: Extending PYTHONPATH with paths
['/Users/chenzhiyu/Downloads/copymanga-downloader']
244 INFO: checking Analysis
244 INFO: Building Analysis because Analysis-00.toc is non existent
244 INFO: Initializing module dependency graph...
246 INFO: Caching module graph hooks...
250 INFO: Analyzing base_library.zip ...
1280 INFO: Processing pre-find module path hook distutils from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1319 INFO: distutils: retargeting to non-venv dir '/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9'
2567 INFO: Caching module dependency graph...
2622 INFO: running Analysis Analysis-00.toc
2626 INFO: Analyzing /Users/chenzhiyu/Downloads/copymanga-downloader/main.py
2733 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
3353 INFO: Processing module hooks...
3353 INFO: Loading module hook 'hook-certifi.py' from '/opt/homebrew/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
3355 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3356 INFO: Loading module hook 'hook-lib2to3.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3361 INFO: Loading module hook 'hook-encodings.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3389 INFO: Loading module hook 'hook-distutils.util.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3391 INFO: Loading module hook 'hook-platform.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3392 INFO: Loading module hook 'hook-pickle.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3393 INFO: Loading module hook 'hook-heapq.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3393 INFO: Loading module hook 'hook-difflib.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3394 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3395 INFO: Loading module hook 'hook-sysconfig.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3399 INFO: Loading module hook 'hook-xml.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3432 INFO: Loading module hook 'hook-distutils.py' from '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks'...
3439 INFO: Looking for ctypes DLLs
3447 INFO: Analyzing run-time hooks ...
3448 INFO: Including run-time hook '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_subprocess.py'
3449 INFO: Including run-time hook '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
3450 INFO: Including run-time hook '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
3451 INFO: Including run-time hook '/opt/homebrew/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
3454 INFO: Looking for dynamic libraries
3627 INFO: Looking for eggs
3627 INFO: Using Python library /opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/Python
3630 INFO: Warnings written to /Users/chenzhiyu/Downloads/copymanga-downloader/build/main/warn-main.txt
3643 INFO: Graph cross-reference written to /Users/chenzhiyu/Downloads/copymanga-downloader/build/main/xref-main.html
3649 INFO: checking PYZ
3649 INFO: Building PYZ because PYZ-00.toc is non existent
3649 INFO: Building PYZ (ZlibArchive) /Users/chenzhiyu/Downloads/copymanga-downloader/build/main/PYZ-00.pyz
3852 INFO: Building PYZ (ZlibArchive) /Users/chenzhiyu/Downloads/copymanga-downloader/build/main/PYZ-00.pyz completed successfully.
3855 INFO: EXE target arch: arm64
3855 INFO: Code signing identity: None
3856 INFO: checking PKG
3856 INFO: Building PKG because PKG-00.toc is non existent
3856 INFO: Building PKG (CArchive) main.pkg
5206 INFO: Building PKG (CArchive) main.pkg completed successfully.
5207 INFO: Bootloader /opt/homebrew/lib/python3.9/site-packages/PyInstaller/bootloader/Darwin-64bit/run
5207 INFO: checking EXE
5207 INFO: Building EXE because EXE-00.toc is non existent
5207 INFO: Building EXE from EXE-00.toc
5208 INFO: Copying bootloader EXE to /Users/chenzhiyu/Downloads/copymanga-downloader/dist/main
5209 INFO: Converting EXE to target arch (arm64)
5231 INFO: Removing signature(s) from EXE
5243 INFO: Appending PKG archive to EXE
5245 INFO: Fixing EXE headers for code signing
5248 INFO: Re-signing the EXE
5264 INFO: Building EXE from EXE-00.toc completed successfully.
```

**打包程序**
```
❯ pyinstaller main.spec
60 INFO: PyInstaller: 5.1
60 INFO: Python: 3.9.13
67 INFO: Platform: macOS-12.4-arm64-arm-64bit
70 INFO: UPX is available.
71 INFO: Extending PYTHONPATH with paths
['/Users/chenzhiyu/Downloads/copymanga-downloader']
165 INFO: checking Analysis
169 INFO: checking PYZ
170 INFO: EXE target arch: arm64
170 INFO: Code signing identity: None
170 INFO: checking PKG
171 INFO: Bootloader /opt/homebrew/lib/python3.9/site-packages/PyInstaller/bootloader/Darwin-64bit/run
171 INFO: checking EXE
```

**运行打包好的程序**
```
❯ ./dist/main
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from turtle import width
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "turtle.py", line 107, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "tkinter/__init__.py", line 37, in <module>
ModuleNotFoundError: No module named '_tkinter'
[11348] Failed to execute script 'main' due to unhandled exception!
```

直接运行main.py是可以正常工作的，打包后不行，猜测可能是main.spec缺了一些需要一起打包的依赖库和数据

### 🧐 解决方案(Solution)
无

### 🚑 其他信息(Other Information)
希望大佬能写个GUI，以及多线程或异步下载功能

**Comment by blacklein** [comment]
**更新解决方案**
通过Github Action Workflow打包可执行程序成功，打包好的程序可以通过终端运行

```
name: python compile(macOS)

on: workflow_dispatch # Manually run workflow

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2.4.2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          
      - name: Compile exe
        run: |
          pyinstaller -F main.py
          pyinstaller main.spec
          
      - name : upload artifact
        uses: actions/upload-artifact@master
        with:
          name: macos-latest
          path: dist/
```

打包过程和我在自己的macbook上的一样，不知道为何action打包就能成功

**Comment by misaka10843** [comment]
> **更新解决方案** 通过Github Action Workflow打包可执行程序成功，打包好的程序可以通过终端运行 <img alt="截屏2022-07-07 11 02 06" width="815" src="https://user-images.githubusercontent.com/69177971/177685581-929301b8-32cd-4c37-b6b4-c36e5b511599.png">
> 
> ```
> name: python compile(macOS)
> 
> on: workflow_dispatch # Manually run workflow
> 
> jobs:
>   macos-build:
>     runs-on: macos-latest
>     steps:
>       - name: Check out git repository
>         uses: actions/checkout@v2.4.2
>       
>       - name: Set up Python 3.10
>         uses: actions/setup-python@v4.0.0
>         with:
>           python-version: "3.10"
>           
>       - name: Install dependencies
>         run: |
>           pip3 install pyinstaller
>           pip3 install -r requirements.txt
>           
>       - name: Compile exe
>         run: |
>           pyinstaller -F main.py
>           pyinstaller main.spec
>           
>       - name : upload artifact
>         uses: actions/upload-artifact@master
>         with:
>           name: macos-latest
>           path: dist/
> ```
> 
> 打包过程和我在自己的macbook上的一样，不知道为何action打包就能成功

感谢大佬修复了action🤣
因为没有macos所以就没有测试过🤣
