### ISSUE TITLE
🐛[BUG]  运行错误

### ISSUE THREAD

**Issue by dfmjndm** [misaka10843/copymanga-downloader#34]
下载时输入漫画名称后出错，环境：python3.9

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbb19f6ae50>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.copymanga.info', port=443): Max retries exceeded with url: /api/v3/search/comic?format=json&limit=20&offset=0&platform=3&q=%E4%B8%8E%E9%9B%AA%E5%A5%B3%E5%90%91%E8%9F%B9%E5%8C%97%E8%A1%8C (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbb19f6ae50>: Failed to establish a new connection: [Errno -2] Name or service not known')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/copymanga-downloader/main.py", line 448, in <module>
    welcome()
  File "/copymanga-downloader/main.py", line 442, in welcome
    manga_search(manga_name)
  File "/copymanga-downloader/main.py", line 150, in manga_search
    response = requests.get(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.copymanga.info', port=443): Max retries exceeded with url: /api/v3/search/comic?format=json&limit=20&offset=0&platform=3&q=%E4%B8%8E%E9%9B%AA%E5%A5%B3%E5%90%91%E8%9F%B9%E5%8C%97%E8%A1%8C (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbb19f6ae50>: Failed to establish a new connection: [Errno -2] Name or service not known')))

**Comment by misaka10843** [comment]
请问操作系统以及版本？
（因为可能是系统或者版本原因）

**Comment by dfmjndm** [comment]
已查明，原因在于启动时询问填写代理那边回复了   n
什么都不回复直接按回车就行了
