### ISSUE TITLE
下载几话后出现如下报错

### ISSUE THREAD

**Issue by dfmjndm** [misaka10843/copymanga-downloader#35]
希望添加下载失败后重新运行时从断点继续

Traceback (most recent call last):
  File "/copymanga-downloader/main.py", line 450, in <module>
    manga_download()
  File "/copymanga-downloader/main.py", line 302, in manga_download
    response = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by misaka10843** [comment]
请问是否使用了最新版本，最新版本理论来说已经添加了重试功能了（但不排除无法进行重试下载）

**Comment by dfmjndm** [comment]
是最新版本

**Comment by misaka10843** [comment]
> 是最新版本

那可能就无解了🤣（以我的能力范围内🤣）
因为copymanga现在限制了请求量，只要一段时间内过多就会ban，量是多少似乎是不定的🤣

**Comment by dfmjndm** [comment]
可以出一个再次运行程序时从上次的结束位置开始下载的版本吗，不用输入第几话到第几话那种，这样下载失败了我也可以用cron下载完整

**Comment by misaka10843** [comment]
> 可以出一个再次运行程序时从上次的结束位置开始下载的版本吗，不用输入第几话到第几话那种，这样下载失败了我也可以用cron下载完整

可以，近期安排qwq

**Comment by blacklein** [comment]
我这边macOS 运行报错有点不一样，一个是正在下载那边没有上面截图这种每张图的提示出来，就正在下载一行字转圈圈，但文件夹里是确实在下载，就是看不到进度，然后每次下载完还必定报下面这个错误信息，subscribe订阅copymanga吗？
```
Traceback (most recent call last):
  File "/Users/chenzhiyu/.local/bin/copymanga-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/chenzhiyu/.local/pipx/venvs/copymanga-dl/lib/python3.11/site-packages/main.py", line 713, in main
    welcome()
  File "/Users/chenzhiyu/.local/pipx/venvs/copymanga-dl/lib/python3.11/site-packages/main.py", line 137, in welcome
    chapter_allocation(manga_chapter_json)
  File "/Users/chenzhiyu/.local/pipx/venvs/copymanga-dl/lib/python3.11/site-packages/main.py", line 548, in chapter_allocation
    if ARGS.subscribe == "1":
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'subscribe'
```

**Comment by misaka10843** [comment]
> 
因为本身其实就是直接放个下载中的loading，进度啥的感觉有点多余所以就没有用（其实是自己懒的写x）

其实` ARGS.subscribe`这个错误已经改了，因为没有使用命令行参数所以导致ARGS无值，但是还没推上来x

**Comment by misaka10843** [comment]
> 我这边macOS 运行报错有点不一样，一个是正在下载那边没有上面截图这种每张图的提示出来，就正在下载一行字转圈圈，但文件夹里是确实在下载，就是看不到进度，然后每次下载完还必定报下面这个错误信息，subscribe订阅copymanga吗？
> 
> ```
> Traceback (most recent call last):
>   File "/Users/chenzhiyu/.local/bin/copymanga-dl", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/Users/chenzhiyu/.local/pipx/venvs/copymanga-dl/lib/python3.11/site-packages/main.py", line 713, in main
>     welcome()
>   File "/Users/chenzhiyu/.local/pipx/venvs/copymanga-dl/lib/python3.11/site-packages/main.py", line 137, in welcome
>     chapter_allocation(manga_chapter_json)
>   File "/Users/chenzhiyu/.local/pipx/venvs/copymanga-dl/lib/python3.11/site-packages/main.py", line 548, in chapter_allocation
>     if ARGS.subscribe == "1":
>        ^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'subscribe'
> ```

因为本身其实就是直接放个下载中的loading，进度啥的感觉有点多余所以就没有用（其实是自己懒的写x）

其实 ARGS.subscribe这个错误已经改了，因为没有使用命令行参数所以导致ARGS无值，但是还没推上来x

**Comment by misaka10843** [comment]
如果没啥问题了的话就关闭议题啦qwq
出现问题了或者还是不行就重新打开吧qwq
