### ISSUE TITLE
🐛[BUG] ModuleNotFoundError: No module named 'cbz'

### ISSUE THREAD

**Issue by hyrulelinks** [misaka10843/copymanga-downloader#92]
### 📷 复现步骤(Steps to Reproduce)

使用README中的pip方式安装，报找不到cbz模块错误。
下载源码，将源码放进src文件夹，在src上层放pyproject.toml，然后python -m build打包，再用pip安装包，运行仍然报找不到cbz错
python main.py运行源码不报错

```
Traceback (most recent call last):
  File "/.local/bin/copymanga-dl", line 7, in <module>
    from main import main
  File "venvs/copymanga-dl/lib/python3.10/site-packages/main.py", line 17, in <module>
    from cbz import create_cbz
ModuleNotFoundError: No module named 'cbz'
```

### 🚑 基本信息(Basic Information)

- 程序版本或action构件日期(Program Version or Action component date):
- 系统(OS): 
- 是否使用了代理(Are agents used): 

Python 3.10
copymanga downloader 3.5 source code
macOS sonoma 14.4
未使用代理

**Comment by hyrulelinks** [comment]
另外想问下，最新更新后，账号密码或token变成强制性要求了吗？没有不用登录的选项了
